
- name: "Container for app"
  docker_container:
    name: "app"
    image: "{{docker_repo}}/image_name"
    state: startedfiles
    restart_policy: unless-stopped
    networks:
      - name: "{{docker_network_name}}"

- name: "Container for app2"
  docker_container:
    name: "app2"
    image: "{{docker_repo}}/image_name2"
    state: started
    restart_policy: unless-stopped
